title: Stackbit Ampersand Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: grid
palette: green
header:
  title: Sudarshan Sawandkar
  logo_img_alt: Ampersand Logo
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: About
      url: /about
      style: link
    - label: Style Guide
      url: /style-guide
      style: link
    - label: Contact
      url: /contact
      style: link
footer:
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Create yours <a
    href="https://app.stackbit.com/create?theme=ampersand&utm_source=deployed-footer"
    target="_blank" rel="noopener">now</a>.
  has_social: true
  social_links:
    - label: GitHub
      url: 'https://github.com/sudarshansb143'
      style: icon
      icon_class: github
      new_window: true
    - label: DEV
      url: 'https://dev.to/sudarshansb143'
      style: icon
      icon_class: dev
      new_window: true
  has_subscribe: true
  subscribe_title: Subscribe for new updates
  subscribe_content: >-
    Subscribe to my email newsletter to receive useful articles and special
    offers. This monthly email is sent out on the first of every month.
  subscribe_action: /subscribe-success
  links:
    - label: Generated from DEV
      url: 'https://dev.to/connecting-with-stackbit'
      new_window: true
      style: link
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
